########################################
# Font
########################################
font_family JetBrains Mono
font_size   12

########################################
# Transparency
########################################
# 0.0 = fully transparent
# 1.0 = fully opaque
# 90% see-through → 10% opacity:
background_opacity 0.8

